version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ppt_data:/app/storage/generated_ppts
    environment:
      - TZ=Asia/Taipei
      - ALLOWED_ORIGINS=http://localhost:3000,https://app-reviews-ai-v3.vercel.app
      - STORAGE_DIR=/app/storage/generated_ppts
      - CORS_ALLOW_CREDENTIALS=true
    restart: unless-stopped

volumes:
  ppt_data:
    driver: local 