version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./generated_ppts:/app/generated_ppts
    environment:
      - TZ=Asia/Taipei
      - ALLOWED_ORIGINS=http://localhost:3000,https://app-reviews-ai-v3.vercel.app
    restart: unless-stopped 