version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./generated_ppts:/app/generated_ppts
    environment:
      - TZ=Asia/Taipei
    restart: unless-stopped 