version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ppt_data:/app/storage/generated_ppts
    environment:
      - TZ=Asia/Taipei
      - ALLOWED_ORIGINS=*
      - STORAGE_DIR=/app/storage/generated_ppts
    restart: unless-stopped

volumes:
  ppt_data:
    driver: local 